/**
 * Lyzer Edge — InstitutionalEvidenceGraphEngine
 * Institutional Evidence Graph Engine.
 * Supports Evidence Relationship Types:
 *   - Evidence supports Decision
 *   - Evidence contradicts Hypothesis
 *   - Evidence generated by Experiment
 *   - Evidence derived from Observation
 */

export class InstitutionalEvidenceGraphEngine {
  constructor() {
    this._disposed = false;
    this._evidenceLinks = [];
  }

  /**
   * Adds a claim-evidence link.
   * @param {string} evidenceId
   * @param {string} targetId
   * @param {string} relation - e.g. 'SUPPORTS_DECISION', 'CONTRADICTS_HYPOTHESIS'
   * @param {number} [confidence=0.95]
   */
  linkEvidence(evidenceId, targetId, relation, confidence = 0.95) {
    this._assertNotDisposed();

    const link = Object.freeze({
      linkId: `ev_link_${evidenceId}_${targetId}`,
      evidenceId,
      targetId,
      relation,
      confidence,
      linkedAt: Date.now()
    });

    this._evidenceLinks.push(link);
    return link;
  }

  /**
   * Solves evidence claim strength for a decision target.
   * @param {string} targetId
   */
  evaluateClaimSupport(targetId) {
    this._assertNotDisposed();

    const supporting = this._evidenceLinks.filter(l => l.targetId === targetId && l.relation.includes('SUPPORTS'));
    const contradicting = this._evidenceLinks.filter(l => l.targetId === targetId && l.relation.includes('CONTRADICTS'));

    const supportScore = supporting.reduce((acc, curr) => acc + curr.confidence, 0);
    const contradictScore = contradicting.reduce((acc, curr) => acc + curr.confidence, 0);
    const netEvidenceStrength = Math.max(0, Math.min(1.0, Math.round((supportScore - contradictScore) * 100) / 100));

    return Object.freeze({
      targetId,
      netEvidenceStrength,
      supportingCount: supporting.length,
      contradictingCount: contradicting.length,
      evaluatedAt: Date.now()
    });
  }

  _assertNotDisposed() {
    if (this._disposed) throw new Error('ERR_INSTITUTIONAL_EVIDENCE_GRAPH_DISPOSED: Institutional Evidence Graph Engine is disposed');
  }

  dispose() {
    this._disposed = true;
    this._evidenceLinks = [];
  }

  [Symbol.dispose]() {
    this.dispose();
  }
}
