/**
 * Lyzer Edge - Metrics Registry Core (Prometheus Integration)
 * Isolates prom-client initialization and metric definitions.
 */

let client = null;
try {
  client = (await import('prom-client')).default;
} catch (e) {
  // prom-client or opentelemetry dependency unavailable in dev environment
}

class DummyMetric {
  inc() {}
  observe() {}
  set() {}
}

const createMetric = (Type, options) => {
  try {
    if (!Type) return new DummyMetric();
    return new Type(options);
  } catch (err) {
    return new DummyMetric();
  }
};

let reg = { metrics: () => '' };
if (client) {
  try {
    reg = new client.Registry();
    client.collectDefaultMetrics({ register: reg, prefix: 'lyzer_runtime_' });
  } catch (e) {
    console.warn('[Observability] prom-client initialization warning:', e.message);
  }
}

export const register = reg;

export const ticksReceivedCounter = createMetric(client?.Counter, {
  name: 'lyzer_pipeline_ticks_received_total',
  help: 'Total candle ticks received',
  labelNames: ['symbol', 'source'],
  registers: [register]
});

export const tickProcessingHistogram = createMetric(client?.Histogram, {
  name: 'lyzer_pipeline_tick_processing_duration_seconds',
  help: 'Tick processing duration in seconds',
  labelNames: ['symbol', 'status'],
  buckets: [0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.010, 0.025, 0.050, 0.100, 0.250, 0.500, 1.0],
  registers: [register]
});

export const csrlProcessingHistogram = createMetric(client?.Histogram, {
  name: 'lyzer_pipeline_csrl_processing_duration_seconds',
  help: 'CSRL tensor alignment processing duration in seconds',
  labelNames: ['symbol'],
  buckets: [0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.010, 0.025, 0.050, 0.100],
  registers: [register]
});

export const cclistEvaluationHistogram = createMetric(client?.Histogram, {
  name: 'lyzer_pipeline_cclist_evaluation_duration_seconds',
  help: 'C-CLIST oracle stress evaluation duration in seconds',
  labelNames: ['symbol'],
  buckets: [0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.010, 0.025, 0.050],
  registers: [register]
});

export const ecaEvaluationsCounter = createMetric(client?.Counter, {
  name: 'lyzer_constitution_evaluations_total',
  help: 'Total ECA Court evaluations',
  labelNames: ['symbol', 'decision'],
  registers: [register]
});

export const constitutionalVetoCounter = createMetric(client?.Counter, {
  name: 'lyzer_constitution_veto_total',
  help: 'Total ECA Court veto decisions by reason code',
  labelNames: ['symbol', 'reason_code'],
  registers: [register]
});

export const riskGatewayLatencyHistogram = createMetric(client?.Histogram, {
  name: 'lyzer_constitution_risk_gateway_latency_seconds',
  help: 'Risk Gateway IPC gRPC latency in seconds',
  labelNames: ['service', 'status'],
  buckets: [0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.010, 0.025, 0.050, 0.100],
  registers: [register]
});

export const sqliteWriteDurationHistogram = createMetric(client?.Histogram, {
  name: 'lyzer_persistence_sqlite_write_duration_seconds',
  help: 'SQLite write operation duration in seconds',
  labelNames: ['operation'],
  buckets: [0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.010, 0.025, 0.050, 0.100],
  registers: [register]
});

export const sqliteLockWaitHistogram = createMetric(client?.Histogram, {
  name: 'lyzer_persistence_sqlite_lock_wait_seconds',
  help: 'SQLite lock wait duration in seconds',
  labelNames: ['db_name'],
  buckets: [0.0001, 0.0005, 0.001, 0.0025, 0.005, 0.010, 0.025, 0.050],
  registers: [register]
});

export const systemErrorsCounter = createMetric(client?.Counter, {
  name: 'lyzer_system_errors_total',
  help: 'Total system exceptions and errors',
  labelNames: ['component', 'error_type'],
  registers: [register]
});

export const signalGeneratedCounter = createMetric(client?.Counter, {
  name: 'lyzer_pipeline_signal_generated_total',
  help: 'Total signals generated by the base signal layer',
  labelNames: ['symbol', 'signal'],
  registers: [register]
});

export const kernelEvaluatedCounter = createMetric(client?.Counter, {
  name: 'lyzer_pipeline_kernel_evaluated_total',
  help: 'Total kernel evaluations completed',
  labelNames: ['symbol', 'eef', 'epistemic_authority'],
  registers: [register]
});

export const breakEvenTradesCounter = createMetric(client?.Counter, {
  name: 'lyzer_pipeline_break_even_trades_total',
  help: 'Total trades protected by break-even trailing stop',
  labelNames: ['symbol', 'direction'],
  registers: [register]
});

export const breakEvenTrades = breakEvenTradesCounter;
export const tradesProtected = breakEvenTradesCounter;

export const activeConnectionsGauge = createMetric(client?.Gauge, {
  name: 'lyzer_system_active_connections',
  help: 'Active network connections by protocol',
  labelNames: ['protocol'],
  registers: [register]
});
