/**
 * @fileoverview Lyzer Edge — Active Runtime Configuration
 *
 * @generated
 * THIS FILE IS A GENERATED ARTIFACT.
 * DO NOT EDIT MANUALLY.
 *
 * Generated by  : v0.2
 * Execution ID  : v02-1780460715458
 * Timestamp     : 2026-06-03T04:25:15.458Z
 * Decision      : TIGHTENED
 * Reason        : maxDD=29.33% > limit=10%
 * Previous      : threshold=52, version=0.1.1
 *
 * @invariant Runtime receives configuration. Runtime never resolves configuration.
 */

/** @type {Readonly<{ version: string, validFrom: string, confidenceThreshold: number }>} */
export const activeConfig = Object.freeze({
  version: '0.1.2',
  validFrom: '2026-06-03T04:25:15.458Z',
  confidenceThreshold: 54,
});
 