import fs from 'fs';
import path from 'path';

const DATA_DIR = process.env.DATA_DIR || path.join(process.cwd(), '.data');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

const SHADOW_LOG_PATH = path.join(DATA_DIR, 'shadow_veto_ledger.jsonl');

/**
 * ShadowLogger: 
 * Tracks ALL signals generated by providers, regardless of TruthKernel Veto.
 * Specifically designed for Experiment 3.5 (Prospective Shadow Validation).
 */
export class ShadowLogger {
  
  /**
   * Log an incoming signal and its TruthKernel evaluation outcome.
   */
  static logSignalOutcome(symbol, timestamp, direction, entryPrice, micro, kernelResult) {
    try {
      const isVetoed = !kernelResult.eef || kernelResult.epistemic_authority === 'VETO';
      const reason = isVetoed ? (kernelResult.reason_codes[0] || 'UNKNOWN_VETO') : 'PASS';
      
      const record = {
        trade_id: `SHADOW_${symbol}_${timestamp}`,
        timestamp,
        symbol,
        direction,
        entry_price: entryPrice,
        
        // Features
        sma20_distance_pct: micro?.sma20DistancePct || 0,
        atr_pct: micro?.atr14_pct || 0,
        lhds: micro?.lhds || 0,
        regime: micro?.regime || 'UNKNOWN',
        
        // Veto Data
        veto_status: isVetoed ? 'REJECT' : 'PASS',
        veto_reason: reason,
        
        provider_id: 'V1', // Currently V1 is the primary provider passing direction
        truth_kernel_verdict: kernelResult.epistemic_authority,
        
        // Counterfactual Excursion (To be populated later)
        counterfactual: {
          mfe_5m: null, mae_5m: null,
          mfe_15m: null, mae_15m: null,
          mfe_30m: null, mae_30m: null,
          mfe_60m: null, mae_60m: null,
          pnl_15m: null, pnl_30m: null, pnl_60m: null
        }
      };
      
      fs.appendFileSync(SHADOW_LOG_PATH, JSON.stringify(record) + '\n', 'utf8');
      
      if (isVetoed && reason.includes('ENTRY_VETO')) {
        console.log(`[SHADOW TRACKER] ${symbol} ${direction} VETOED by TruthKernel. Reason: ${reason} (SMA: ${(record.sma20_distance_pct*100).toFixed(2)}%, ATR: ${(record.atr_pct*100).toFixed(2)}%)`);
      }
      
    } catch (e) {
      console.error('[SHADOW TRACKER] Failed to log shadow outcome', e);
    }
  }

  /**
   * Simulates/Resolves counterfactual PnL after 15m.
   * This would typically be a background cron job in production.
   */
  static updateForwardExcursions(symbol, currentCandle) {
    // In a real implementation, this would load pending shadow trades, 
    // evaluate their MFE/MAE against the new candle, and close them at 15m.
  }
}
